### ISSUE TITLE
Errors finding libccd when building on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by johnwason** [ros-industrial-consortium/tesseract#191]
When trying to build on Windows Subsytem for Linux I am getting some weird errors. With `catkin_make_isolated`, I am getting this error.

`
from /home/wasonj/catkin_ws/src/tesseract/tesseract/tesseract_collision/src/fcl/fcl_utils.cpp:56:
/home/wasonj/catkin_ws/devel_isolated/fcl/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd.h:41:10: fatal error: ccd/ccd.h: No such file or directory
 #include <ccd/ccd.h>
          ^~~~~~~~~~~
`

With `catkin build`, I am getting this error:

`
Errors     << tesseract_collision:make /home/wasonj/catkin_ws/logs/tesseract_collision/build.make.000.log
/usr/bin/ld: cannot find -lccd
collect2: error: ld returned 1 exit status
make[2]: *** [libtesseract_collision_fcl.so] Error 1
make[1]: *** [CMakeFiles/tesseract_collision_fcl.dir/all] Error 2
make: *** [all] Error 2
`

It appears something is wrong with how libccd is referenced.

**Comment by haudren** [comment]
I can :+1: this issue: building the latest tesseract on a clean install fails to find `libccd`. Reason is as follows:
- Tesseract changed how fcl is found between 168d730f553fd086fc2995b2c9e8cc9615b69bd4 and 4848d7fc8c3f1e5e98d67efaae45c027f9ed7b7d :
```
--- a/tesseract/tesseract_collision/CMakeLists.txt
+++ b/tesseract/tesseract_collision/CMakeLists.txt
@@ -4,22 +4,17 @@ project(tesseract_collision VERSION 0.1.0 LANGUAGES CXX)
 find_package(Eigen3 REQUIRED)
 find_package(Boost COMPONENTS system thread program_options REQUIRED)
 find_package(octomap REQUIRED)
-find_package(PkgConfig REQUIRED)
-find_package(ccd REQUIRED)
 find_package(console_bridge REQUIRED)
 find_package(tesseract_geometry REQUIRED)
 find_package(tesseract_common REQUIRED)
 find_package(Bullet REQUIRED)
-
-pkg_check_modules(LIBFCL REQUIRED fcl)
-find_library(LIBFCL_LIBRARIES_FULL ${LIBFCL_LIBRARIES} ${LIBFCL_LIBRARY_DIRS})
-set(LIBFCL_LIBRARIES "${LIBFCL_LIBRARIES_FULL}")
-list(APPEND LIBFCL_LIBRARIES ${CCD_LIBRARIES})
+find_package(fcl REQUIRED)
``` 
- Main difference is that we no longer look for `ccd` explicitly
- `fcl` does not look for `ccd` in its `fclConfig.cmake`
- `ccd` does not have a prefix

Thus when building the ros workspace from scratch:
- `ccd` is built and installed into `ws/devel/lib/libccd.so`
- `tesseract_collision` happily builds along even though the `ccd` target does not exist because it's not qualified. Includes are correctly found.
- Linking fails because `gcc` looks for libraries in default locations (no dice) and in `LIBRARY_PATH` (not `LD_LIBRARY_PATH` ) which is not set by default.

Note: CI passes because the `tesseract_ext` libraries are installed in `/usr/local/lib` in the docker image, not sure how it was built.

Possible remedies:
- Update FCL to actually add the dependency to their CMake config file
- Look for CCD explicitly alongside fcl
