### ISSUE TITLE
Unit Tests fail in Code Coverage build

### ISSUE THREAD

**Issue by mpowelson** [ros-industrial-consortium/tesseract#294]
This is mentioned in #292 but is happening in nightly builds as well.

**Comment by Levi-Armstrong** [comment]
Only during code coverage build the FCL BVH contact manager return 299 contacts for the large scale test when it should return 300. Though during the kinetic and melodic build it passes. 

The plan is to dump all contacts information to a csv to track down which one it is missing to help determine the root cause.

**Comment by Levi-Armstrong** [comment]
This seems to have gone away on its own. Not sure what was going on but we will this open for a bit to see if it shows up again.

**Comment by mpowelson** [comment]
@Levi-Armstrong This hasn't popped up again has it? Should we close this?
